### PR TITLE
Fix "now" being returned for undefined internal value

### PR DESCRIPTION
**Pull request by gastonelhordoy**

### CODE REVIEW

**Comment by gastonelhordoy** [comment]
Hey @Aldaviva, I made a couple of changes so null values are preserved as null and also there is no need to use .valueOf() in every query condition. I'm using this in my project and their work as expected.

**Comment by Aldaviva** [comment]
Thanks @gastonelhordoy!

**Comment by Aldaviva** [comment]
I'll try to cut a release and publish to NPM and update the contributors list later today or tomorrow.

**Comment by Aldaviva** [comment]
Oh wow this was opened a long time ago. I don't know why GitHub isn't sending me emails when pull requests are opened. Sorry for the delay.

**Comment by gastonelhordoy** [comment]
Yup... actually only the first commit was from last November, the second one was made just today.
Thanks Ben!

**Pull request merged**
