### PR TITLE
New Query Methods

### PR DESCRIPTION
**Pull request by brad-decker**
Checking to see if you're interested in adding something like this to the library. I feel like it would be a nice shortcut and would read well in the code. I would implement the full suite of normal moment queries (before, after, etc) and any others you would find relevant. I have implemented between here for you to review.

Thanks.

### CODE REVIEW

**Comment by brad-decker** [comment]
@Aldaviva IS this library abandoned or was my pull request not adequate/wanted? Thanks.

**Comment by Aldaviva** [comment]
Sorry, I never got notified there was a pull request. Will take a look shortly.

**Comment by Aldaviva** [comment]
Looks good, thanks for your contribution Brad! I would be happy for you to continue working on this.

It sounds like you wish to implement additional methods, so let me know whenever you want me to merge this in.

**Comment by brad-decker** [comment]
No problem! Thanks for taking a look. Let me add in some additional queries and ill let you know.

**Comment by gastonelhordoy** [comment]
@Aldaviva , are you planning to merge this PR and release a new version?

**Comment by brad-decker** [comment]
@Aldaviva @gastonelhordoy I believe i'm the hold up here. @Aldaviva if you want to merge this in i can create another pull request with the additional methods when i have bandwidth. Pretty busy @ work right now.

**Comment by gastonelhordoy** [comment]
@brad-decker I see, I understood this was a first PR and then you would add more stuff later in a new PR.
@Aldaviva maybe we can have this merged as is and then slowly release new features whenever @brad-decker  is free to keep extending the functionality.

**Comment by Aldaviva** [comment]
Works for me. I will get this merged and released shortly.

**Comment by Aldaviva** [comment]
Merged, bumped version to 0.1.0, published to NPM, added @brad-decker to contributors.

**Comment by gastonelhordoy** [comment]
Sweet, thanks man!

**Pull request merged**
